/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-06-07 05:21:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.template.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.8.jar", Long.valueOf(1621247903980L));
    _jspx_dependants.put("jar:file:/Users/isaac/Documents/isaacProject/TeamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MTA/WEB-INF/lib/tiles-jsp-3.0.8.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1506773284000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1620617528803L));
    _jspx_dependants.put("jar:file:/Users/isaac/Documents/isaacProject/TeamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MTA/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script>\r\n");
      out.write("//장르별 이동\r\n");
      out.write("$(\".music_genre\").click(function() {\r\n");
      out.write("\t$(\"#m_genre\").val($(this).html());\r\n");
      out.write("\t\t\r\n");
      out.write("\tconsole.log($(this).html());\r\n");
      out.write("\tvar sk = $(this).html();\r\n");
      out.write("\t$(\"#cat_form\").attr({\r\n");
      out.write("\t\t\"method\" : \"GET\",\r\n");
      out.write("\t\t\"action\" : \"/mboard/boardList\"\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#cat_form\").submit();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("        <!--좌측 슬라이드바  -->\r\n");
      out.write("           <input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("           <label for=\"menuicon\">\r\n");
      out.write("              <span></span>\r\n");
      out.write("              <span></span>\r\n");
      out.write("              <span></span>\r\n");
      out.write("           </label>\r\n");
      out.write("              <div class=\"sidebar\">\r\n");
      out.write("                  <div class=\"categori\">\r\n");
      out.write("                  <form id =\"cat_form\" ><input type =\"hidden\" name =\"m_genre\" id =\"m_genre\" />\r\n");
      out.write("                  </form>\r\n");
      out.write("                     <h3 id=\"music_font\" class=\"music_genre\">Ballad</h3>\r\n");
      out.write("                    \r\n");
      out.write("                     <h3 id=\"music_font\" class=\"music_genre\">Electronic</h3>\r\n");
      out.write("                  \r\n");
      out.write("                     <h3 id=\"music_font\" class=\"music_genre\">RnB</h3>\r\n");
      out.write("                   \r\n");
      out.write("                     <h3 id=\"music_font\" class=\"music_genre\">NewAge</h3>\r\n");
      out.write("                   \r\n");
      out.write("                     <h3 id=\"music_font\" class=\"music_genre\">Rap/Hiphop</h3>\r\n");
      out.write("                     <br><br><hr>\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <h3 id=\"music_font\" onclick=\"location.href='/nboard/listnews'\">News Board</h3>\r\n");
      out.write("                    \r\n");
      out.write("                     <h3 id=\"music_font\" class=\"community\">Community</h3>\r\n");
      out.write("                     <h3 id=\"music_font\" onclick=\"location.href='/sboard/serviceCenter'\">About</h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <div id=mainhomepagecategori>\r\n");
      out.write("      <form id=\"mainnpageform\">       \r\n");
      out.write("      <div id=\"topcategori\">\r\n");
      out.write("         <div id=\"leftcategori\">\r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("            <span id=\"mtaintro\" class=\"topmainpagebutton\">MTA 소개</span>\r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("            <span id=\"introhomepage\"class=\"topmainpagebutton\">MTA Intro</span>\r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"rightcategori\">   \r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("<!--     <span class=\"block\">  |  </span> -->\r\n");
      out.write("            \r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("            <span class=\"topmainpagebutton\" onclick=\"location.href='/sboard/serviceCenter'\">Customer Service Center</span>\r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("            <span class=\"topmainpagebutton\" onclick=\"location.href='/board/freeboard'\">Notice</span>   \r\n");
      out.write("            <span class=\"block\">  |  </span>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("             <!-- 메인페이지 제목-->\r\n");
      out.write("      <div id=\"buttoncategori\">\r\n");
      out.write("         <div id=\"buttoncategoriserve\">\r\n");
      out.write("            <h1 id=\"homepage_name\" class=\"mainpagebutton\">Music TradeAssociate</h1>\r\n");
      out.write("            <p id=\"homepage_servename\">Sell or Buy Various Genres Of Music and Copyrights!</p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>   \r\n");
      out.write("   </div>\r\n");
      out.write("   <hr>\r\n");
      out.write("             \r\n");
      out.write("\r\n");
      out.write("       <!-- 우측 슬라이드바  -->\r\n");
      out.write("          <label class=\"inner\" id=\"inner\" >\r\n");
      out.write("          <div id=\"logindiv\">\r\n");
      out.write("              <div id=\"main_page\">\r\n");
      out.write("                 \r\n");
      out.write("              </div>\r\n");
      out.write("             <br><br>          \r\n");
      out.write("              <h1 id=\"mypagefont\">Sign in</h1>\r\n");
      out.write("              <br><br><hr><br>\r\n");
      out.write("              <div id=\"idpwddiv\">\r\n");
      out.write("              <form name=\"loginform\" id=\"loginform\">\r\n");
      out.write("                 <p id=\"idpwd\">ID</p>\r\n");
      out.write("                 <input type=\"text\" class=\"login\" name=\"user_id\" id=\"user_id\">\r\n");
      out.write("                 <p id=\"idpwd\">Passward</p>\r\n");
      out.write("                 <input type=\"password\" class=\"login\" name=\"user_passwd\" id=\"user_passwd\">\r\n");
      out.write("              <br><br>\r\n");
      out.write("              <input type=\"button\" class=\"login_button\" id=\"login_button\" name=\"login_button\" value=\"Log In\">\r\n");
      out.write("              </form>\r\n");
      out.write("              <br />\r\n");
      out.write("              <br>\r\n");
      out.write("              <a  href=\"/user/Accept\" class=\"sign_upbutton\" id=\"new_login\" >Sign up</a>\r\n");
      out.write("              <a  href=\"/user/useridfind\" class=\"sign_upbutton\" id=\"id.pwd\">ID Search</a>/\r\n");
      out.write("              <a  href=\"/user/userpwfind\" class=\"sign_upbutton\" id=\"id.pwd\">Password Search</a>\r\n");
      out.write("              </div>\r\n");
      out.write("           </div>\r\n");
      out.write("           </label>\r\n");
      out.write("           <div id=\"mypage\">\r\n");
      out.write("              <form name=\"mypageform\" id=\"mypageform\">\r\n");
      out.write("              <div id=\"my_page\">   \r\n");
      out.write("                 </div>  \r\n");
      out.write("              <br><br>\r\n");
      out.write("              <h1 id=\"mypagefont\">MyPage</h1>\r\n");
      out.write("             <br><br><hr><br>\r\n");
      out.write("             <input type=\"button\" id=\"mypage_board\" class=\"button\" value=\"Membership Information\">\r\n");
      out.write("             <br><br>\r\n");
      out.write("             <input type=\"button\" id=\"mypage_vente\" class=\"button\" value=\"Sales Inquiry\">\r\n");
      out.write("             <br><br>\r\n");
      out.write("             <input type=\"button\" id=\"mypage_purchase\" class=\"button\" value=\"Purchase List\">\r\n");
      out.write("             <br><br>\r\n");
      out.write("             <input type=\"button\" id=\"mypage_shopping\" class=\"button\" onclick=\"location.href='/order/cartList'\" value=\"Shopping Basket\">\r\n");
      out.write("             <br><br>\r\n");
      out.write(" \t\t\t <input type=\"button\" id=\"mypage_logout\" class=\"button\" value=\"log Out\">\r\n");
      out.write("             </form> \r\n");
      out.write("              </div>\r\n");
      out.write("              ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/template/client/header.jsp(63,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userInfo.user_id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<span  id=mypagebutton class=\"topmainpagebutton\">MyPage</span>\r\n");
          out.write("            \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<span  id=mypagelogin class=\"topmainpagebutton\">Login</span>\r\n");
          out.write("            \t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
