/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-23 09:33:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.template.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.8.jar", Long.valueOf(1621247903980L));
    _jspx_dependants.put("jar:file:/Users/isaac/Documents/isaacProject/TeamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mtaProject/WEB-INF/lib/tiles-jsp-3.0.8.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1506773284000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- 문서 유형 : 현재 웹 문서가 어떤 HTML 버전에 맞게 작성되었는지를 알려준다. -->\r\n");
      out.write("\r\n");
      out.write("<!--<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("     DTD 선언문이 HTML 페이지의 가장 첫 라인에 명시되어야 웹 브라우저가 HTML 버전을 인식.\r\n");
      out.write("     HTML태그나 CSS를 해당 버전에 맞도록 처리하므로 웹 표준 준수를 위하여 반드시 명시되어야 한다.-->\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("   \r\n");
      out.write("      <meta charset=\"UTF-8\" />\r\n");
      out.write("      <!-- html4 : 파일의 인코딩 방식 지정 -->\r\n");
      out.write("      <!--<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />-->\r\n");
      out.write("\r\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\" />\r\n");
      out.write("      <!-- 브라우저의 호환성 보기 모드를 막고, 해당 브라우저에서 지원하는 가장 최신 버전의 방식으로 HTML 보여주도록 설정.-->\r\n");
      out.write("      \r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("      <!--viewport : 화면에 보이는 영역을 제어하는 기술. width는 device-width로 설정(브라우저 너비를 장치 너비에 맞추어 표시). initial-scale는 초기비율(보이는 영역과 웹 페이지를 맞춤). user-scalable는 사용자가 화면축소를 하지 못하도록 설정.-->\r\n");
      out.write("         \r\n");
      out.write("      <!-- 모바일 웹 페이지 설정 -->\r\n");
      out.write("      <link rel=\"shortcut icon\" href=\"../image/icon.png\" />\r\n");
      out.write("      <link rel=\"apple-touch-icon\" href=\"../image/icon.png\" />\r\n");
      out.write("      <!-- 모바일 웹 페이지 설정 끝 -->\r\n");
      out.write("      \r\n");
      out.write("      <!--[if lt IE 9]>\r\n");
      out.write("      \r\n");
      out.write("      <script src =\"../js/html5shiv.js\"></script>\r\n");
      out.write("      <![endif]-->\r\n");
      out.write("    \t<link href=\"/resources/include/css/leftslide.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t<link href=\"/resources/include/css//intro/intro.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t<link href=\"/resources/include/css/intro/intrologin.css\" rel=\"stylesheet\"/>\r\n");
      out.write("      <title>MTA에 오신걸 환영합니다.</title>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"/resources/include/js/jquery-3.6.0.min.js\">\r\n");
      out.write("      </script>\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      var clicks = 0;\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t\t/* 음악 게시판 바로가기   */\r\n");
      out.write("\t\t\t\t$(\".musicBoardMenu\").click(function(){\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/board/boardList\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 사인업 버튼 */\r\n");
      out.write("\t\t\t\t $(\"#login_page\").click(function(){\r\n");
      out.write("\t\t    \t\t  if (clicks == 0) {\r\n");
      out.write("\t\t    \t\t\t  $(\".inner\").addClass(\"open\");\r\n");
      out.write("\t\t    \t\t\t  clicks++;\r\n");
      out.write("\t\t    \t\t\t  console.log(clicks);\r\n");
      out.write("\t\t    \t\t  }else{\r\n");
      out.write("\t\t  \t\t\t\t\r\n");
      out.write("\t\t \t\t\t\t $(\".inner\").removeClass(\"open\");\r\n");
      out.write("\t\t \t\t    \t\r\n");
      out.write("\t\t \t\t\t\t \r\n");
      out.write("\t\t \t\t\t\t clicks--;\r\n");
      out.write("\t\t \t\t\t\tconsole.log(clicks);\r\n");
      out.write("\t\t \t\t\t}\r\n");
      out.write("\t\t    \t  });\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t/* 안어 클래스 엑스div */\r\n");
      out.write("\t\t\t\t $(\"#intro_page\").click(function(){\r\n");
      out.write("\t\t\t\t\t  $(\".inner\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t /* 마이페이지 버튼 */\r\n");
      out.write("\t\t\t\t  $(\"#login_button\").click(function(){\r\n");
      out.write("\t\t    \t\t  $(\"#mypage\").addClass(\"open\");\r\n");
      out.write("\t\t    \t  });\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t  /* 마이페이지 버튼 */\r\n");
      out.write("\t\t    \t  $(\"#my_page\").click(function(){\r\n");
      out.write("\t\t    \t\tlocation.href='/'; \r\n");
      out.write("\t\t    \t  });\r\n");
      out.write("\t\t});\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("     </script>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("   \t<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("   \t<label for=\"menuicon\">\r\n");
      out.write("   \t\t<span></span>\r\n");
      out.write("   \t\t<span></span>\r\n");
      out.write("   \t\t<span></span>\r\n");
      out.write("   \t</label>\r\n");
      out.write("   \t<div class=\"sidebar\">\r\n");
      out.write("   \t <div class=\"categori\">\r\n");
      out.write("   \t\t<h3 class = \"musicBoardMenu\">Music Board</h3>\r\n");
      out.write("   \t \t<h3>Ballad</h3>\r\n");
      out.write("   \t \t<br>\r\n");
      out.write("   \t \t<h3>Rock</h3>\r\n");
      out.write("   \t \t<br>\r\n");
      out.write("   \t \t<h3>R&B</h3>\r\n");
      out.write("   \t \t<br>\r\n");
      out.write("   \t \t<h3>New Age</h3>\r\n");
      out.write("   \t \t<br>\r\n");
      out.write("   \t \t<h3>Rap/Hiphop</h3>\r\n");
      out.write("   \t \t<br><br><hr>\r\n");
      out.write("   \t \t<br><br>\r\n");
      out.write("   \t \t<h3>News Board</h3>\r\n");
      out.write("   \t \t<br>\r\n");
      out.write("   \t \t\r\n");
      out.write("   \t \t<h3>Community</h3>\r\n");
      out.write("   \t \t<br>\r\n");
      out.write("   \t \t<h3>About</h3>\r\n");
      out.write("\r\n");
      out.write("   \t </div>\r\n");
      out.write("   \t</div>\r\n");
      out.write("  \t<img src=\"/resources/include/img/logo_main.png\" id=\"main_logo\">\t\r\n");
      out.write("  \t<div id=\"login.page\">\t\r\n");
      out.write("  \t\t<h1 id=\"main_name\">Music Trade Associate</h1>\r\n");
      out.write("  \t\t<h3 id=\"main_survename\">A record label for creators</h3><br/>\r\n");
      out.write("  \t\t<a href=\"/mainpage/mainpagenotlogin\" class=\"myButton\" id=main_home>Open Main Home</a>\r\n");
      out.write("  \t\t<a href=\"#\" class=\"myButton\" id=\"login_page\">Sign Up</a>\r\n");
      out.write("  \t\t<video id=\"video\" src=\"/resources/include/video/lostsky.mp4\" width=\"600\" controls autoplay></video>\r\n");
      out.write("  \t\t<label class=\"inner\" id=\"inner\" >\r\n");
      out.write("  \t\t\t<div id=\"logindiv\">\r\n");
      out.write("  \t\t\t\t<div id=\"intro_page\">\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" \t\t\t\t<br><br> \t\t\t\r\n");
      out.write("  \t\t\t\t<h1>Sign Up</h1>\r\n");
      out.write("  \t\t\t\t<br><br><hr><br>\r\n");
      out.write("  \t\t\t\t<div id=\"idpwddiv\">\r\n");
      out.write("  \t\t\t\t\t<p id=\"idpwd\">ID</p>\r\n");
      out.write("  \t\t\t\t\t<input type=\"text\" class=\"login\" id=\"id_login\">\r\n");
      out.write("  \t\t\t\t\t<p id=\"idpwd\">Passward</p>\r\n");
      out.write("  \t\t\t\t\t<input type=\"password\" class=\"login\"  id=\"psw_login\">\r\n");
      out.write("  \t\t\t\t<br><br>\r\n");
      out.write("  \t\t\t\t<input type=\"button\" id=\"login_button\" value=\"Log In\">\r\n");
      out.write("  \t\t\t\t<br />\r\n");
      out.write("  \t\t\t\t<br>\r\n");
      out.write("  \t\t\t\t<a href=\"#\" class=\"new_login\" id=\"new_login\">회원가입</a>\r\n");
      out.write("  \t\t\t\t<a href=\"#\" class=\"id.pwd\" id=\"id.pwd\">아이디/비밀번호 찾기</a>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t</label>\t\r\n");
      out.write("  \t\t\t<div id=\"mypage\">\r\n");
      out.write("  \t\t\t\t<div id=\"my_page\">\t\r\n");
      out.write("  \t\t\t\t</div>   \r\n");
      out.write("  \t\t\t\t<br><br>\r\n");
      out.write("  \t\t\t\t<h1>마이페이지</h1>\r\n");
      out.write(" \t\t\t\t<br><br><hr><br>\r\n");
      out.write(" \t\t\t\t<input type=\"button\" id=\"mypage_board\" class=\"mypage_shop\" value=\"회원정보\">\r\n");
      out.write(" \t\t\t\t<br><br>\r\n");
      out.write(" \t\t\t\t<input type=\"button\" id=\"mypage_vente\" class=\"mypage_shop\" value=\"판매내역\">\r\n");
      out.write(" \t\t\t\t<br><br>\r\n");
      out.write(" \t\t\t\t<input type=\"button\" id=\"mypage_purchase\" class=\"mypage_shop\" value=\"구매내역\">\r\n");
      out.write(" \t\t\t\t<br><br>\r\n");
      out.write(" \t\t\t\t<input type=\"button\" id=\"mypage_shopping\" class=\"mypage_shop\" value=\"장바구니\">\r\n");
      out.write(" \t\t\t\t<br><br>\r\n");
      out.write(" \t\t\t\t<input type=\"button\" id=\"mypage_about\" class=\"mypage_shop\" value=\"고객센터\">\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\t\t\r\n");
      out.write("  \t\t<div class=\"sidebar1\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<nav >\r\n");
      out.write(" \t\t\t<audio src=\"/resources/include/audio/01.mp3\" controls autoplay loop></audio>\r\n");
      out.write("  \t\t</nav>\r\n");
      out.write("  \t</div>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
