/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-29 06:55:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/isaac/Documents/isaacProject/TeamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mtaProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1620617528802L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- 문서 유형 : 현재 웹 문서가 어떤 HTML 버전에 맞게 작성되었는지를 알려준다. -->\r\n");
      out.write("\r\n");
      out.write("<!--<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("     DTD 선언문이 HTML 페이지의 가장 첫 라인에 명시되어야 웹 브라우저가 HTML 버전을 인식.\r\n");
      out.write("     HTML태그나 CSS를 해당 버전에 맞도록 처리하므로 웹 표준 준수를 위하여 반드시 명시되어야 한다.-->\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- html5 : 파일의 인코딩 방식 지정 - 한국어 처리를 위한 euc-kr과 다국어 처리를 위한 utf-8로 설정.-->\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<!-- html4 : 파일의 인코딩 방식 지정 -->\r\n");
      out.write("\t\t<!--<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />-->\r\n");
      out.write("\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\" />\r\n");
      out.write("\t\t<!-- 브라우저의 호환성 보기 모드를 막고, 해당 브라우저에서 지원하는 가장 최신 버전의 방식으로 HTML 보여주도록 설정.-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("\t\t<!--viewport : 화면에 보이는 영역을 제어하는 기술. width는 device-width로 설정(브라우저 너비를 장치 너비에 맞추어 표시). initial-scale는 초기비율(보이는 영역과 웹 페이지를 맞춤). user-scalable는 사용자가 화면축소를 하지 못하도록 설정.-->\r\n");
      out.write("      \t\r\n");
      out.write("\t\t<!-- 모바일 웹 페이지 설정 -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"/resources/images/icon.png\" />\r\n");
      out.write("\t\t<link rel=\"apple-touch-icon\" href=\"/resources/images/icon.png\" />\r\n");
      out.write("\t\t<!-- 모바일 웹 페이지 설정 끝 -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/include/dist/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/include/dist/css/bootstrap-theme.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src =\"/resources/include/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"/resources/include/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\"src =\"/resources/include/js/common.js\"></script> \r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"../js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\"#boardInsertBtn\").click(function(){\r\n");
      out.write("\t\t\t\t\t//입력값 체크 \r\n");
      out.write("\t\t\t\t\tif(!chkData(\"#m_title\",\"이름을\"))return ;\r\n");
      out.write("\t\t\t\t\telse if(!chkData(\"#m_name\",\"제목을\")) return;\r\n");
      out.write("\t\t\t\t\telse if(!chkData(\"#coverImg\",\"커버이미지를 \")) return ; //to-do  파일 등록에 대한 유효성 체크 구문을 다르게 주어, 메서드 생성 \r\n");
      out.write("\t\t\t\t\telse if(!chkData(\"#m_bpm\",\"Bpm 정보를\")) return ;\r\n");
      out.write("\t\t\t\t\telse if(!chkData(\"#m_explain\",\"곡 설명을\")) return ;\r\n");
      out.write("\t\t\t\t\telse if(!chkData(\"#file\",\"음악파일을\")) return ;\r\n");
      out.write("\t\t\t\t\telse if(!chkData(\"#m_price\",\"가격을\")) return ;\r\n");
      out.write("\t\t\t\t\t//else if(!chkData(\"#\",\"\")) return ;\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_writeForm\").attr({\r\n");
      out.write("\t\t\t\t\t\t\t\"method\":\"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\"enctype\":\"multipart/form-data\",\r\n");
      out.write("\t\t\t\t\t\t\t\"action\":\"/board/boardInsert\"\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_writeForm\").submit();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//입력값 초기화\r\n");
      out.write("\t\t\t\t$(\"#boardCancelBtn\").click(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#f_writeForm\").each(function(){\r\n");
      out.write("\t\t\t\t\t\tthis.reset();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t//목록 돌아가기\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#boardListBtn\").click(function(){\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/board/boardList\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t// 무료 배포 선택 여부에 따라 금액 입력 비활성화 설정. \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"input[name ='m_isfree']\").click(function(){\r\n");
      out.write("\t\t\t\t\tif($(\"input[name ='m_isfree']:checked\").val()== \"1\"){\r\n");
      out.write("\t\t\t\t\t\t$(\"#m_price\").attr(\"disabled\",true);\r\n");
      out.write("\t\t\t\t\t\t$(\"#m_price\").attr(\"placeholder\",\"무료배포\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#m_price\").attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\t\t$(\"#m_price\").attr(\"placeholder\",\"판매 희망 금액\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t});// 최상위 종료.\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<title>WriteForm.jsp</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class =\"container\">\r\n");
      out.write("\t\t\t<!-- \t<h2 class =\"text-center\">글작성</h2> -->\r\n");
      out.write("\r\n");
      out.write("\t\t<form id=\"f_writeForm\">\r\n");
      out.write("\t\t\t<input type =\"hidden\" id =\"user_id\" name = \"user_id\" value =\"test\"/> <!-- session 값으로 추후 로그인 정보 전달 요망 --> \r\n");
      out.write("\t\t\t<table class=\"table table-light\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"17%\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"33%\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"17%\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"33%\" />\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_title\" class=\"text-left\">Title : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"m_title\" id=\"m_title\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"게시글 제목을 입력하세요\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_name\" class=\"text-left\">Track Title\r\n");
      out.write("\t\t\t\t\t\t\t\t: </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"m_name\" id=\"m_name\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"곡 제목을 입력하세요\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_coverimage\" class=\"text-left\">Cover\r\n");
      out.write("\t\t\t\t\t\t\t\tImage Attachment : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"file\" name=\"coverImg\" id=\"coverImg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<!-- 업로드 할 파일 미리보기가 출력될 영역 설정 예정  -->\r\n");
      out.write("\t\t\t\t\t\t<td hidden=\"true\"><span class = \"preview\"></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_bpm\">BPM : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"m_bpm\" id=\"m_bpm\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"BPM 정보 입력\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_explain\">Description : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><textarea name=\"m_explain\" id=\"m_explain\" cols=\"30\"\r\n");
      out.write("\t\t\t\t\t\t\t\trows=\"10\" style=\"resize: none;\" placeholder=\"곡 설명\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_file\">File(wav,mp3) : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"file\" name=\"file\" id=\"file\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_isfree\">Distribute for Free : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name = \"m_isfree\" value = \"1\" ><label class = \" \">Y</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name = \"m_isfree\" value =\"0\"><label class = \" \">N</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for=\"m_price\">Price : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"m_price\" id=\"m_price\" \r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"판매 희망 금액\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><label for =\"m_genre\">Genre : </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><select name =\"m_genre\" id = \"m_genre\" >\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"genre\">Genre</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"ballad\">Ballad</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"Rock\">Rock</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"r&b\">R&B</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"new age\">New Age</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"rap\">Rap/Hip-hop</option>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"저장\" id=\"boardInsertBtn\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-success\" /> <input type=\"button\" value=\"취소\"\r\n");
      out.write("\t\t\t\t\tid=\"boardCancelBtn\" class=\"btn btn-success\" /> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"목록\" id=\"boardListBtn\" class=\"btn btn-success\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
